#!/bin/sh

# simple xinit startup script
picom &         # composite manager
setbg &         # wallpaper script
remaps & 	# keyboard remapping script
dunst &         # notification daemon
slstatus &      # statusbar application
sxhkd &         # simple x hotkey daemon
mpd &           # music player daemon
exec dwm 	# run dwm
