#!/bin/sh

# simple xinit startup script
remaps & 	# run keyboard remapping script
dunst &
status &        # run statusbar script
sxhkd &         # run hotkey daemon
mpd &           # run music player daemon
exec dwm 	# run dwm
